context.modules = [
    # {   name = libpipewire-module-loopback
    #     args = {
    #         node.description = "E2x2 (IN1 L)"
    #         capture.props = {
    #             node.name = "capture.E2x2_1"
    #             audio.position = [ FL ]
    #             stream.dont-remix = true
    #             target.object = "alsa_input.usb-Topping_E2x2-00.analog-surround-21"
    #             node.passive = true
    #         }
    #         playback.props = {
    #             node.name = "interface-in1_l"
    #             media.class = "Audio/Source"
    #             audio.position = [ MONO ]
    #         }
    #     }
    # }
    # {   name = libpipewire-module-loopback
    #     args = {
    #         node.description = "E2x2 (IN2 R)"
    #         capture.props = {
    #             node.name = "capture.E2x2_2"
    #             audio.position = [ FR ]
    #             stream.dont-remix = true
    #             target.object = "alsa_input.usb-Topping_E2x2-00.analog-surround-21"
    #             node.passive = true
    #         }
    #         playback.props = {
    #             node.name = "interface_in2_r"
    #             media.class = "Audio/Source"
    #             audio.position = [ MONO ]
    #         }
    #     }
    # }
]
