# context.modules = [
#   { name = libpipewire-module-loopback
#     args = {
#       capture.props = {
#         node.name = "chat_audio_sink"       # Virtual sink for chat audio
#         node.description = "Voice Chat Audio"
#         media.class = "Audio/Sink"
#         stream.capture.sink = true
#       }
#       playback.props = {
#         node.target = "alsa_output.usb-Topping_E2x2-00.analog-surround-21"
#       }
#     }
#   }
#   { name = libpipewire-module-loopback
#     args = {
#       capture.props = {
#         node.name = "game_audio_sink"       # New virtual sink for game audio
#         node.description = "Game Audio"
#         media.class = "Audio/Sink"
#         stream.capture.sink = true
#       }
#       playback.props = {
#         node.target = "alsa_output.usb-Topping_E2x2-00.analog-surround-21"
#       }
#     }
#   }
# ]
